language: minimal

services:
  - docker

script:
  - docker pull morfin/myalpine:OpenCV4.2.0WithDebugWithCatch2.11.1 > /dev/null
  - docker run --name biometry -d -ti morfin/myalpine:OpenCV4.2.0WithDebugWithCatch2.11.1 /bin/bash
  - docker cp ../biometry biometry:/src/biometry
  - docker exec -ti biometry /bin/bash -c "mkdir biometry/release biometry/debug"
  - docker exec -ti biometry /bin/bash -c "cd biometry/release; cmake -DCMAKE_BUILD_TYPE=Release ..; cmake --build . --config Release"
  - docker exec -ti biometry /bin/bash -c "cd biometry/debug; cmake -DCMAKE_BUILD_TYPE=Debug ..; cmake --build . --config Debug"
  - docker exec -ti biometry /bin/bash -c "cd biometry/release; ctest -C Release -j 1"
  - docker exec -ti biometry /bin/bash -c "cd biometry/debug; ctest -C Debug -j 1"
