include(cmake/tools.cmake)

function(setup_coverage)
    IF($CACHE{BUILD_ENABLE_COVERAGE} AND NOT CMAKE_BUILD_TYPE STREQUAL "Debug")
        message(FATAL_ERROR "BUILD_ENABLE_COVERAGE=ON works only together with CMAKE_BUILD_TYPE=Debug!!!")
    ELSEIF($CACHE{BUILD_ENABLE_COVERAGE} AND CMAKE_BUILD_TYPE STREQUAL "Debug")
        STRING(REPLACE / \\ WINDOWS_SRC_DIR ${CMAKE_SOURCE_DIR})
        STRING(REPLACE / \\ WINDOWS_BINARY_DIR ${CMAKE_BINARY_DIR})
        get_all_libraries(LIBS)
        SET(MERGE_CMD "OpenCppCoverage.exe;")
        SET(COVERAGE_TARGETS "")
        FOREACH(LIB ${LIBS})
            get_directory_property(LIB_TARGETS DIRECTORY ${CMAKE_SOURCE_DIR}/libs/${LIB} BUILDSYSTEM_TARGETS)
            LIST(FIND LIB_TARGETS ${LIB}_tests LIB_TEST_FOUND)
            IF(NOT (LIB_TEST_FOUND EQUAL -1))
                SET(COMMAND "OpenCppCoverage.exe;-q;--modules;${LIB};--sources;${WINDOWS_SRC_DIR}\\libs\\${LIB}\\include\\*;--sources;${WINDOWS_SRC_DIR}\\libs\\${LIB}\\src\\*;--export_type;binary:coverage_results/${LIB}_tests.cov;--;${WINDOWS_BINARY_DIR}\\bin\\Debug\\${LIB}_tests.exe;")
                add_custom_target(COVERAGE_${LIB} ALL COMMAND ${COMMAND} DEPENDS "${LIB}_tests")
                set_target_properties(COVERAGE_${LIB} PROPERTIES FOLDER "coverage")
                LIST(APPEND MERGE_CMD "--input_coverage;coverage_results/${LIB}_tests.cov;")
                LIST(APPEND COVERAGE_TARGETS "COVERAGE_${LIB}")
            ENDIF()
        ENDFOREACH()
        LIST(APPEND MERGE_CMD "--export_type;html:coverage_results/Coverage;--export_type;cobertura:coverage_results/Coverage.xml;")
        add_custom_target(COVERAGE ALL COMMAND ${MERGE_CMD} DEPENDS ${COVERAGE_TARGETS})
        set_target_properties(COVERAGE PROPERTIES FOLDER "coverage")
    ENDIF()
endfunction()
