MACRO(SUBDIRLIST result curdir)
  FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
  SET(dirlist "")
  FOREACH(child ${children})
    IF(IS_DIRECTORY ${curdir}/${child})
      LIST(APPEND dirlist ${child})
    ENDIF()
  ENDFOREACH()
  SET(${result} ${dirlist})
ENDMACRO()

function(get_all_libraries result)
    SUBDIRLIST(SUBDIRS ${CMAKE_SOURCE_DIR}/libs)
    SET(${result} ${SUBDIRS} PARENT_SCOPE)
endfunction()